=== josukewee/PRI/www/xml/notes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:simpleType name="languageType">
    <xsd:restriction base="xsd:string"/>
  </xsd:simpleType>

  <xsd:element name="notes">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="note" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="title">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="xsd:string">
                      <xsd:attribute name="jazyk" type="languageType" use="required"/>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="author" type="xsd:string"/>
              <xsd:element name="content">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="xsd:string">
                      <xsd:attribute name="category" type="xsd:string"/>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="created_at" type="xsd:dateTime"/>
              <xsd:element name="updated_at" type="xsd:dateTime"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== josukewee/PRI/www/xml/notes.xml
<?xml version="1.0" encoding="UTF-8"?>
<notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="notes.xsd">
  <note>
    <title jazyk="en">Walk the doggy</title>
    <author>pavel</author>
    <content category="general">Lorem ipsum dolor sit amet, consectetur adipiscing 7 elit. In sagittis ullamcorper nisl, eget 8 ultricies enim ultrices.</content>
    <created_at>2024-06-18T10:00:00</created_at>
    <updated_at>2024-06-18T10:00:00</updated_at>
  </note>
  <note>
    <title jazyk="en">finish the project</title>
    <author>pavel</author>
    <content category="work">Lorem ipsum dolor sit amet, consectetur adipiscing 7 elit. In sagittis ullamcorper nisl, eget 8 ultricies enim ultrices.</content>
    <created_at>2024-06-18T11:00:00</created_at>
    <updated_at>2024-06-18T11:00:00</updated_at>
  </note>
  <note>
    <title jazyk="en">Text my sibling</title>
    <author>pavel</author>
    <content category="personal">This is the third note content, personal.</content>
    <created_at>2024-06-18T12:00:00</created_at>
    <updated_at>2024-06-18T12:00:00</updated_at>
  </note>
  <note>
    <title jazyk="en">Buy a bread</title>
    <author>pavel</author>
    <content category="general">This is the fourth note content.</content>
    <created_at>2024-06-18T13:00:00</created_at>
    <updated_at>2024-06-18T13:00:00</updated_at>
  </note>
  <note>
    <title jazyk="en">Meeting with Michel</title>
    <author>pavel</author>
    <content category="work">Some really important things should be discussed.</content>
    <created_at>2024-06-18T14:00:00</created_at>
    <updated_at>2024-06-18T14:00:00</updated_at>
  </note>
  <note>
    <title jazyk="en">HHH</title>
    <author>pavel</author>
    <content category="personal">This is the sixth note content, personal.</content>
    <created_at>2024-06-18T15:00:00</created_at>
    <updated_at>2024-06-18T15:00:00</updated_at>
  </note>
  <note>
    <title jazyk="en">Seventh Note</title>
    <author>pavel</author>
    <content category="general">This is the seventh note content.</content>
    <created_at>2024-06-18T16:00:00</created_at>
    <updated_at>2024-06-18T16:00:00</updated_at>
  </note>
  <note>
    <title jazyk="en">Eighth Note</title>
    <author>pavel</author>
    <content category="work">This is the eighth note content, related to work.</content>
    <created_at>2024-06-18T17:00:00</created_at>
    <updated_at>2024-06-18T17:00:00</updated_at>
  </note>
  <note>
    <title jazyk="en">Ninth Note</title>
    <author>pavel</author>
    <content category="personal">This is the ninth note content, personal.</content>
    <created_at>2024-06-18T18:00:00</created_at>
    <updated_at>2024-06-18T18:00:00</updated_at>
  </note>
  <note>
    <title jazyk="en">Tenth Note</title>
    <author>pavel</author>
    <content category="general">This is the tenth note content.</content>
    <created_at>2024-06-18T19:00:00</created_at>
    <updated_at>2024-06-18T19:00:00</updated_at>
  </note>
  <note>
    <title jazyk="en">Love isqqq around</title>
    <author>pavel</author>
    <content category="general">Lorem ipsssssssssum dolor sit amet, consectetur adipiscing 7 elit. In sagittis ullamcorper nisl, eget 8 ultricies enim ultrices.</content>
    <created_at>2024-06-18T22:00:00</created_at>
    <updated_at>2024-06-18T22:00:00</updated_at>
  </note><note>
    <title jazyk="en">Love iseeeearound</title>
    <author>pavel</author>
    <content category="general">Lorem ipsssssssssum dolor sit amet, consectetur adipiscing 7 elit. In sagittis ullamcorper nisl, eget 8 ultricies enim ultrices.</content>
    <created_at>2024-06-18T22:00:00</created_at>
    <updated_at>2024-06-18T22:00:00</updated_at>
  </note><note>
    <title jazyk="en">Love istttt around</title>
    <author>pavel</author>
    <content category="general">Lorem ipsssssssssum dolor sit amet, consectetur adipiscing 7 elit. In sagittis ullamcorper nisl, eget 8 ultricies enim ultrices.</content>
    <created_at>2024-06-18T22:00:00</created_at>
    <updated_at>2024-06-18T22:00:00</updated_at>
  </note><note>
    <title jazyk="en">Hate ihhhhs around</title>
    <author>pavel</author>
    <content category="work">Lorem ipsssssssssum dolor sit amet, consectetur adipiscing 7 elit. In sagittis ullamcorper nisl, eget 8 ultricies enim ultrices.</content>
    <created_at>2024-06-18T22:00:00</created_at>
    <updated_at>2024-06-18T22:00:00</updated_at>
  </note><note>
    <title jazyk="en">Hate issada around</title>
    <author>pavel</author>
    <content category="work">Lorem ipsssssssssum dolor sit amet, consectetur adipiscing 7 elit. In sagittis ullamcorper nisl, eget 8 ultricies enim ultrices.</content>
    <created_at>2024-06-18T22:00:00</created_at>
    <updated_at>2024-06-18T22:00:00</updated_at>
  </note><note>
    <title jazyk="en">Hate iaaaas around</title>
    <author>alena</author>
    <content category="work">Lorem ipsssssssssum dolor sit amet, consectetur adipiscing 7 elit. In sagittis ullamcorper nisl, eget 8 ultricies enim ultrices.</content>
    <created_at>2024-06-18T22:00:00</created_at>
    <updated_at>2024-06-18T22:00:00</updated_at>
  </note></notes>
